// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.HandHistoryEntry = (function(superClass) {
    extend(HandHistoryEntry, superClass);

    function HandHistoryEntry() {
      return HandHistoryEntry.__super__.constructor.apply(this, arguments);
    }

    HandHistoryEntry.prototype.initialize = function(hands) {
      this.set("playerHand", hands["playerHand"]);
      return this.set("dealerHand", hands["dealerHand"]);
    };

    return HandHistoryEntry;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=HandHistoryEntry.js.map
