// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.BackgroundView = (function(superClass) {
    extend(BackgroundView, superClass);

    function BackgroundView() {
      return BackgroundView.__super__.constructor.apply(this, arguments);
    }

    BackgroundView.prototype.tagName = 'svg';

    BackgroundView.prototype.className = 'background';

    BackgroundView.prototype.initialize = function() {
      this.render();
      this.addChips();
      this.model.on('change:money', this.addChips, this);
      return this.model.on('playerWin', this.fireworks, this);
    };

    BackgroundView.prototype.fireworks = function() {
      var center, colors, range;
      this.board.selectAll('.fireworks').remove();
      center = {
        y: innerHeight / 2,
        x: innerWidth / 2
      };
      colors = d3.scale.category10();
      range = d3.range(500);
      return this.board.selectAll('circle').data(range).enter().append('circle').classed('fireworks', true).attr('r', 20).style('fill', function(d, i) {
        return colors(i % 10);
      }).attr('cy', center.x).attr('cx', center.y).transition().duration(1000).attr('cy', function() {
        return (Math.random() - 0.5) * 2000 + center.y;
      }).attr('cx', function() {
        return (Math.random() - 0.5) * 2000 + center.y;
      }).style('opacity', 0);
    };

    BackgroundView.prototype.addChips = function() {
      var chips, j, numchips, results;
      numchips = Math.floor((this.model.get('money')) / 100);
      numchips = Math.min(numchips, 10000);
      if (numchips > 0) {
        chips = (function() {
          results = [];
          for (var j = 1; 1 <= numchips ? j <= numchips : j >= numchips; 1 <= numchips ? j++ : j--){ results.push(j); }
          return results;
        }).apply(this);
      } else {
        chips = [];
      }
      this.board.selectAll('image').data(chips, function(key) {
        return key;
      }).enter().append('image').attr('xlink:href', 'https://cdn0.iconfinder.com/data/icons/casino-poker-cards-and-chips/154/casino-chip-gamble-game-128.png').classed('moneychip', true).attr('width', 50).attr('height', 50).attr('y', 0).attr('x', 0).transition().duration(1000).attr('y', function() {
        return Math.random() * 200 + 200;
      }).attr('x', function() {
        return Math.random() * 200 + 300;
      });
      return this.board.selectAll('image').data(chips).exit().remove();
    };

    BackgroundView.prototype.render = function() {
      return this.board = (d3.select('.background')).attr('height', window.innerHeight).attr('width', window.innerWidth);
    };

    return BackgroundView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=BackgroundView.js.map
