// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    return new AppView({
      model: new App()
    }).$el.appendTo('body');
  });

}).call(this);

//# sourceMappingURL=main.js.map
